apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: it-helpdesk
type: Opaque
stringData:
  POSTGRES_USER: helpdesk_app
  POSTGRES_PASSWORD: helpdesk123
  POSTGRES_DB: helpdesk_db
