# IT Helpdesk Helm Chart values

namespace: it-helpdesk

replicaCount:
  postgres: 1
  userService: 1
  ticketService: 1
  notificationService: 1
  frontend: 1

images:
  postgres:
    repository: it-helpdesk-postgres
    tag: v1

  userService:
    repository: it-helpdesk-user-service
    tag: v2

  ticketService:
    repository: it-helpdesk-ticket-service
    tag: v6

  notificationService:
    repository: it-helpdesk-notification-service
    tag: v4

  frontend:
    repository: it-helpdesk-frontend
    tag: v1

service:
  postgres:
    port: 5432

  userService:
    port: 8001

  ticketService:
    port: 8002

  notificationService:
    port: 8003

  frontend:
    port: 80

postgres:
  database: helpdesk_db
  username: helpdesk_app
  password: helpdesk123
  storage:
    size: 5Gi
    accessMode: ReadWriteOnce
    storageClass: it-helpdesk-storage

database:
  host: it-helpdesk-postgres
  port: 5432

ingress:
  enabled: true
  className: nginx
  host: ""
