apiVersion: v1
kind: Service
metadata:
  name: user-service
  namespace: it-helpdesk
spec:
  selector:
    app: user-service
  ports:
    - protocol: TCP
      port: 8001
      targetPort: 8001
  type: ClusterIP