apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: it-helpdesk
  namespace: argocd

spec:
  project: default

  sources:
    # Source 1: Helm chart
    - repoURL: https://github.com/sumeetp121/it-helpdesk.git
      targetRevision: main
      path: helm/it-helpdesk
      helm:
        valueFiles:
          - $values/gitops/it-helpdesk-values.yaml

    # Source 2: GitOps values
    - repoURL: https://github.com/sumeetp121/it-helpdesk.git
      targetRevision: main
      ref: values

  destination:
    server: https://kubernetes.default.svc
    namespace: it-helpdesk

  syncPolicy:
    automated:
      prune: true
      selfHeal: true

    syncOptions:
      - CreateNamespace=true