apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-service
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.replicaCount.notificationService }}

  selector:
    matchLabels:
      app: notification-service

  template:
    metadata:
      labels:
        app: notification-service

    spec:
      imagePullSecrets:
        - name: ghcr-secret
      containers:
        - name: notification-service
          image: "{{ .Values.images.notificationService.repository }}:{{ .Values.images.notificationService.tag }}"
          imagePullPolicy: Always

          env:
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_PASSWORD

          resources:
            requests:
              cpu: "100m"
              memory: "64Mi"
            limits:
              cpu: "250m"
              memory: "128Mi"

          ports:
            - containerPort: 8003