apiVersion: v1
kind: Service
metadata:
  name: notification-service
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: notification-service

  ports:
    - protocol: TCP
      port: {{ .Values.service.notificationService.port }}
      targetPort: {{ .Values.service.notificationService.port }}

  type: ClusterIP