apiVersion: v1
kind: Service
metadata:
  name: it-helpdesk-notification-service
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: notification-service

  ports:
    - protocol: TCP
      port: 8003
      targetPort: 8003

  type: ClusterIP