apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1

  selector:
    matchLabels:
      app: postgres

  template:
    metadata:
      labels:
        app: postgres

    spec:
      containers:
        - name: postgres
          image: it-helpdesk-postgres:v1
          imagePullPolicy: Never

          resources:
            requests:
              cpu: "250m"
              memory: "64Mi"
            limits:
              cpu: "500m"
              memory: "128Mi"

          envFrom:
            - secretRef:
                name: postgres-secret

          volumeMounts:
            - name: postgres-storage
              mountPath: /var/lib/postgresql/data

          ports:
            - containerPort: 5432

      volumes:
        - name: postgres-storage
          persistentVolumeClaim:
            claimName: postgres-pvc