apiVersion: v1
kind: ConfigMap
metadata:
  name: user-service-config
  namespace: {{ .Values.namespace }}
data:
  DB_HOST: "{{ .Values.database.host }}"
  DB_NAME: "{{ .Values.postgres.database }}"
  DB_USER: "{{ .Values.postgres.username }}"
  DB_PORT: "{{ .Values.database.port }}"