apiVersion: v1
kind: Service
metadata:
  name: user-service
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: user-service
  ports:
    - protocol: TCP
      port: {{ .Values.service.userService.port }}
      targetPort: {{ .Values.service.userService.port }}
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: it-helpdesk-user-service
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: user-service
  ports:
    - protocol: TCP
      port: {{ .Values.service.userService.port }}
      targetPort: {{ .Values.service.userService.port }}
  type: ClusterIP