# GitOps desired state for IT Helpdesk
# Image tags are updated by GitHub Actions after successful image builds.

images:
  userService:
    tag: "b51b7aaf6ea390f59da5cded8a6f2975dd9ea981"

  ticketService:
    tag: "b51b7aaf6ea390f59da5cded8a6f2975dd9ea981"

  notificationService:
    tag: "b51b7aaf6ea390f59da5cded8a6f2975dd9ea981"

  frontend:
    tag: "b51b7aaf6ea390f59da5cded8a6f2975dd9ea981"
